
TMPDIR = "${TOPDIR}/tmp-initramfscfg"
DEPLOY_DIR = "${TMPDIR}/deploy"

TCLIBC = "musl"
TCLIBCAPPEND = "-${TCLIBC}"

TARGET_OS = "linux-dummy"
# TARGET_OS:x86-64 = "linux-musl"
# TARGET_OS:aarch64 = "linux-musleabi"

# ---
