paths-ignore:
  - "files/user-keys/boot_keys/*"
  - "files/user-keys/ima_keys/*"
  - "files/user-keys/modsign_keys/*"
  - "files/user-keys/mok_sb_keys/*"
  - "files/user-keys/rpm_keys/*"
  - "files/user-keys/secondary_trusted_keys/*"
  - "files/user-keys/system_trusted_keys/*"
  - "files/user-keys/uefi_sb_keys/*"
