# conf/distro/include/distro-mirrors.conf

# git and tarball generation
BB_GIT_SHALLOW = "1"
BB_GIT_SHALLOW_DEPTH = "1"
BB_GENERATE_MIRROR_TARBALLS = "1"
BB_GENERATE_SHALLOW_TARBALLS = "1"
BB_SIGNATURE_HANDLER = "OEBasicHash"

# remote downloads
INHERIT += "own-mirrors"
SOURCE_MIRROR_URL = "https://downloads.distro-core.brainhoard.com"

BB_HASHSERVE_UPSTREAM = "hashserv.distro-core.brainhoard.com:8686"

# PRSERV_HOST = "localhost:0"
PRSERV_UPSTREAM = "prserv.distro-core.brainhoard.com:8585"

SSTATE_MIRRORS = "file://.* https://sstate-cache.distro-core.brainhoard.com/PATH"
SSTATE_MIRROR_ALLOW_NETWORK = "1"

# ---
