# require conf/distro/include/local-versions.conf

# Used to pin specific packages and versions

# virtual runtime
VIRTUAL-RUNTIME_keymaps ??= "keymaps"
VIRTUAL-RUNTIME_syslog ??= "syslog-ng"

VIRTUAL-RUNTIME_container_engine ??= "docker-moby"
VIRTUAL-RUNTIME_container_runtime ??= "virtual-runc"
VIRTUAL-RUNTIME_container_networking ??= "cni"
# VIRTUAL-RUNTIME_container_orchestration ??= "k3s"
VIRTUAL-RUNTIME_base-utils-nsenter ??= "util-linux-nsenter"

VIRTUAL-RUNTIME_xserver_common ??= "xserver-xorg"
# if "", default xserver-nodm-init
VIRTUAL-RUNTIME_graphical_init_manager ??= "gdm"

PREFERRED_PROVIDER_virtual/libgl ??= "mesa"
PREFERRED_PROVIDER_virtual/libgles1 ??= "mesa"
PREFERRED_PROVIDER_virtual/libgles2 ??= "mesa"
PREFERRED_PROVIDER_virtual/libgles3 ??= "mesa"
PREFERRED_PROVIDER_virtual/xserver ??= "xserver-xorg"
PREFERRED_PROVIDER_virtual/runc ??= "runc-opencontainers"

PREFERRED_RPROVIDER_network-configuration ??= "networkd-dhcp-conf"
PREFERRED_RPROVIDER_virtual/psplash ??= "psplash"

PREFERRED_RPROVIDER_util-linux-fsck-native = "util-linux-fsck-native"
PREFERRED_RPROVIDER_util-linux-agetty-native = "util-linux-agetty-native"
PREFERRED_RPROVIDER_util-linux-mount-native = "util-linux-mount-native"
PREFERRED_RPROVIDER_util-linux-umount-native = "util-linux-umount-native"

# preferred versions
# PREFERRED_VERSION_shim = "15.8"

# Explicitly removed packages
PACKAGE_EXCLUDE:append = " util-linux-more"

# rpi-default-providers.inc
# PREFERRED_PROVIDER_virtual/kernel:sbc-raspberrypi5 ??= "linux-raspberrypi"
# PREFERRED_PROVIDER_virtual/xserver:sbc-raspberrypi5 ?= "xserver-xorg"
PREFERRED_PROVIDER_virtual/egl:sbc-raspberrypi5 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "userland", d)}"
PREFERRED_PROVIDER_virtual/libgles2:sbc-raspberrypi5 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "userland", d)}"
PREFERRED_PROVIDER_virtual/libgl:sbc-raspberrypi5 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "mesa-gl", d)}"
PREFERRED_PROVIDER_virtual/mesa:sbc-raspberrypi5 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "mesa-gl", d)}"
PREFERRED_PROVIDER_virtual/libgbm:sbc-raspberrypi5 ?= "${@bb.utils.contains("MACHINE_FEATURES", "vc4graphics", "mesa", "mesa-gl", d)}"
PREFERRED_PROVIDER_vlc:sbc-raspberrypi5 ?= "rpidistro-vlc"
PREFERRED_PROVIDER_ffmpeg:sbc-raspberrypi5 ?= "rpidistro-ffmpeg"
PREFERRED_PROVIDER_libav:sbc-raspberrypi5 ?= "rpidistro-ffmpeg"
PREFERRED_PROVIDER_libpostproc:sbc-raspberrypi5 ?= "rpidistro-ffmpeg"
PREFERRED_PROVIDER_jpeg:sbc-raspberrypi5 ?= "jpeg"
PREFERRED_PROVIDER_virtual/libomxil:sbc-raspberrypi5 ?= "userland"
PREFERRED_PROVIDER_u-boot-default-script:sbc-raspberrypi5 ??= "rpi-u-boot-scr"

# ---
