# require conf/distro/include/local-mirrors.conf

# Used to supply mirror details

# remote downloads
INHERIT += "own-mirrors"
SOURCE_MIRROR_URL ?= "https://localhost/downloads"

# remote sstate-cache
# SSTATE_MIRRORS ?= "file://.* https://localhost/sstate-cachePATH"
# SSTATE_MIRROR_ALLOW_NETWORK = "1"

# server: bitbake-hashserv --read-only --bind 0.0.0.0:8686 &
# BB_HASHSERVE ?= "localhost:8686"

# server: bitbake-prserv --host 0.0.0.0 --port 8585 --start
# PRSERV_HOST ?= "localhost:8585"

# DL_DIR git and tarball generation
BB_GIT_SHALLOW = "1"
BB_GIT_SHALLOW_DEPTH = "1"
BB_GENERATE_MIRROR_TARBALLS ?= "1"
BB_GENERATE_SHALLOW_TARBALLS ?= "1"

# ---
