# conf/distro/include/distro-mirrors.conf

# Used to supply hashserv/prserv details

# git and tarball generation
BB_GIT_SHALLOW = "1"
BB_GIT_SHALLOW_DEPTH = "1"
BB_GENERATE_MIRROR_TARBALLS = "1"
BB_GENERATE_SHALLOW_TARBALLS = "1"
BB_SIGNATURE_HANDLER = "OEBasicHash"

# local downloads
# DL_DIR = "/nfs/shared/downloads"

# remote downloads NFS
# DL_DIR = "/nfs/downloads"

# remote downloads S3
INHERIT += "own-mirrors"
SOURCE_MIRROR_URL = "s3://downloads.distro-core.brainhoard.com"

# local sstate-cache
# SSTATE_DIR = "/nfs/shared/sstate-cache"
# BB_HASHSERVE = "auto"
# BB_HASHSERVE_UPSTREAM = "hashserv.distro-core.brainhoard.com:8686"
# PRSERV_HOST = "localhost:0"

# remote sstate-cache NFS
# SSTATE_DIR = "/nfs/sstate-cache"

# remote sstate-cache S3
BB_HASHSERVE = "hashserv.distro-core.brainhoard.com:8686"
SSTATE_MIRRORS = "file://.* s3://sstate-cache.distro-core.brainhoard.com/PATH"
SSTATE_MIRROR_ALLOW_NETWORK = "1"
# PRSERV_HOST = "prserv.distro-core.brainhoard.com:8585"

# ---
