# require by conf/local.conf

# set build the hostname or IP
# MIRROR_BUILD_SERVER = "build"

# remote downloads
# INHERIT += "own-mirrors"
# SOURCE_MIRROR_URL ?= "https://${MIRROR_BUILD_SERVER}/downloads"

# remote sstate-cache
# SSTATE_MIRRORS ?= "file://.* https://${MIRROR_BUILD_SERVER}/sstate-cachePATH"
# SSTATE_MIRROR_ALLOW_NETWORK = "1"

# remote bitbake-hashserv; requires running bitbake-servers.service
# server: bitbake-hashserv --bind :8686 &
# BB_HASHSERVE ?= "0.0.0.0:8686"
# BB_HASHSERVE ?= "${MIRROR_BUILD_SERVER}:8686"

# remote bitbake-prserv; requires running bitbake-servers.service
# server: bitbake-prserv --host 0.0.0.0 --port 8585 --start
# PRSERV_HOST ?= "0.0.0.0:8585"
# PRSERV_HOST ?= "${MIRROR_BUILD_SERVER}:8585"

# DL_DIR git and tarball generation
BB_GIT_SHALLOW = "1"
BB_GIT_SHALLOW_DEPTH = "1"
BB_GENERATE_MIRROR_TARBALLS ?= "1"
BB_GENERATE_SHALLOW_TARBALLS ?= "1"

# ---
