#!/bin/sh

: install host dependency

. /etc/os-release

case $ID in

almalinux*)
    sudo sh -c "
        dnf install -y epel-release
        yum install -y dnf-plugins-core
        dnf config-manager --set-enabled crb
        dnf makecache
        dnf upgrade -y
        dnf install -y gawk make wget tar bzip2 gzip python3 unzip perl patch \
            diffutils diffstat git cpp gcc gcc-c++ glibc-devel texinfo chrpath \
            ccache socat perl-Data-Dumper perl-Text-ParseWords perl-Thread-Queue \
            python3-pip python3-GitPython python3-jinja2 python3-pexpect xz which \
            rpcgen zstd lz4 cpio glibc-langpack-en libacl git-lfs hostname
        dnf install -y 'dnf-command(config-manager)'
        dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
        dnf install -y gh --repo gh-cli
    " || exit 1
    ;;

debian* | ubuntu* )
    sudo sh -c "
        apt update -y
        apt upgrade -y
        apt install -y gawk wget git diffstat unzip texinfo gcc build-essential \
            chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils \
            iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool \
            file locales libacl1 git-lfs make libxml2-utils
        locale-gen en_US.UTF-8
        mkdir -p -m 755 /etc/apt/keyrings
        wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
        chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
        echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        apt update
        apt install gh -y
    " || exit 1
    ;;

fedora* )
    sudo sh -c "
        dnf install -y gawk make wget tar bzip2 gzip python3 unzip perl patch diffutils \
            diffstat git cpp gcc gcc-c++ glibc-devel texinfo chrpath ccache perl-Data-Dumper \
            perl-Text-ParseWords perl-Thread-Queue perl-bignum socat python3-pexpect findutils \
            which file cpio python python3-pip xz python3-GitPython python3-jinja2 rpcgen \
            perl-FindBin perl-File-Compare perl-File-Copy perl-locale zstd lz4 hostname \
            glibc-langpack-en libacl
        dnf install 'dnf-command(config-manager)'
        dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
        dnf install gh --repo gh-cli
    " || exit 1
    ;;

opensuse* )
    sudo sh -c "
        zypper install -y python gcc gcc-c++ git chrpath make wget python-xml diffstat \
            makeinfo python-curses patch socat python3 python3-curses tar python3-pip \
            python3-pexpect xz which python3-Jinja2 rpcgen zstd lz4 bzip2 gzip hostname \
            libacl1
        pip3 install GitPython
        zypper addrepo https://cli.github.com/packages/rpm/gh-cli.repo
        zypper ref
        zypper install gh
    " || exit 1
    ;;

* )
    exit 1
    ;;

esac

: install git settings
git config --global http.sslVerify true

: install repo tool
curl https://storage.googleapis.com/git-repo-downloads/repo > $HOME/.local/bin/repo
chmod a+rx $HOME/.local/bin/repo
[ -n "$(command -v repo)" ] || exit 1

exit 0
