#!/bin/bash

# Setup for a new WSL2 instance

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_NAME=$(basename $0)

source /etc/os-release

if [ -n "$(command -v setx.exe)" ]; then
    if [ -z "USERPROFILE" ]; then
        setx.exe GNUPGHOME %USERPROFILE%\.gnupg
        setx.exe WSLENV USERNAME:USERPROFILE/p
        echo "Terminate the WSL2 instance and restart. Run $SCRIPT_NAME again to finalize."
        echo "wsl.exe --shutdown"
        exit 0
    fi
fi

# existing metadata could reflect uid/gid from a different instance; these settings attempt
# to mitigate the difference in uid between different distro if necessary.

if [ -d "$USERPROFILE" ]; then

    if [ ! -e $USERPROFILE/.wslconfig ]; then

    echo "Tune WSL2 service resource use at $USERPROFILE/.wslconfig"

    sudo bash -c "
cat >$USERPROFILE/.wslconfig <<EOF
[wsl2]
# swap=0
# memory=32G
# processors=12
autoProxy=true
vmIdleTimeout=120000

[experimental]
sparseVhd=true
autoMemoryReclaim=dropcache
useWindowsDnsCache=true
EOF
"

    fi

    sudo bash -c "
cat >/etc/sudoers.d/localhost <<EOF
# allow all commands with no-password
$(id -un) ALL=(ALL:ALL) NOPASSWD: ALL
EOF
"

    sudo bash -c "
cat >/etc/wsl.conf <<EOF
[boot]
systemd=true

[automount]
uid=$(id -u)
gid=$(id -g)
options=uid=$(id -u),gid=$(id -g),case=dir,umask=077,fmask=077,dmask=077

[user]
default=$(id -un)
EOF
"

    sudo bash -c "
mkdir -p /mnt/home
cat >/etc/fstab <<EOF
# drvfs mount to a drive letter
# M: /mnt/m drvfs rw,noatime,uid=$(id -u),gid=$(id -g),case=dir,umask=077,fmask=077,dmask=077 0 0
# bind mount to windows user home
# \\\$USERPROFILE /mnt/home none bind,default 0 0
EOF
systemctl daemon-reload
"

    # working folder per doc
    sudo mkdir -p /srv/repo
    sudo chmod 1777 /srv/repo

    # install this script in instance
    [[ -x $SCRIPT_DIR/setup-home-links ]] && sudo install -o root -g root -m 0755 $SCRIPT_DIR/setup-home-links /usr/bin/setup-home-links
    [[ -x $SCRIPT_DIR/setup-host-deps ]] && sudo install -o root -g root -m 0755 $SCRIPT_DIR/setup-host-deps /usr/bin/setup-host-deps

    # Creation of ~/.config WSL2 path at %USERPROFILE%
    mkdir -p $USERPROFILE/.config && ln -sf $USERPROFILE/.config ~/.config
    rm -f ~/.config/.config

    # Creation of ~/.gnupg WSL2 path at %USERPROFILE%
    mkdir -p $USERPROFILE/.gnupg && ln -sf $USERPROFILE/.gnupg ~/.gnupg
    rm -f ~/.gnupg/.gnupg

    # Creation of ~/.local WSL2 path at %USERPROFILE%
    mkdir -p $USERPROFILE/.local && ln -sf $USERPROFILE/.local ~/.local
    rm -f ~/.local/.local

    # Creation of ~/.ssh WSL2 path at %USERPROFILE%
    mkdir -p $USERPROFILE/.ssh && ln -sf $USERPROFILE/.ssh ~/.ssh
    rm -f ~/.ssh/.ssh

    # Creation of ~/.netrc WSL2 path at %USERPROFILE%; obtain personal web token 
    touch $USERPROFILE/.netrc && ln -sf $USERPROFILE/.netrc ~/.netrc

    # example content ~/.netrc
    # machine github.com
    # login username
    # password webtoken
    # EOF

fi

# Install host dependency
[[ -x $SCRIPT_DIR/setup-host-deps ]] && $SCRIPT_DIR/setup-host-deps

echo "Run $SCRIPT_NAME to repeat steps."
echo "Setup keys for git, gpg, and ssh if not already done."

if [ -n "$(command -v setx.exe)" ]; then
    echo "Terminate the WSL2 instance and restart. Run $SCRIPT_NAME again to finalize."
    echo "wsl.exe --shutdown"
fi
