# %SYSCONFDIR%/wsl-distribution.conf

[oobe]
command = %SYSCONFDIR%/oobe.sh
defaultUid = 1000
defaultName = %DISTRO%

[shortcut]
icon = %NONARCH_BASE_LIBDIR%/wsl/terminal-profile.ico

[windowsterminal]
ProfileTemplate = %NONARCH_BASE_LIBDIR%/wsl/terminal-profile.json
