# require by MACHINE.conf

EFI_PROVIDER = "grub-efi"

# GRUB_GFXSERIAL = "1"
# GRUB_CFG = "grub${EFI_ARCH}.cfg"
# GRUB_OPTS = "serial --unit=1 --speed=115200 --word=8 --parity=no --stop=1;terminal_input serial;terminal_output serial;"
# GRUB_ROOT = "PARTUUID=${GPT_PART_UUID_ROOT}"
# GRUB_SERIAL = "console=ttyS1,115200"
# GRUB_TIMEOUT = "60"

# image-live class
# LABELS = ""
# ROOTFS = "${IMAGE_LINK_NAME}"
# INITRD = "${INITRAMFS_IMAGE}-${MACHINE}.${INITRAMFS_FSTYPES}"

BAD_RECOMMENDATIONS:pn-grub-efi += "systemd-boot systemd-bootconf"
BAD_RECOMMENDATIONS:pn-grub-efi += "systemd-boot systemd-bootconf"

# ---
