# require by MACHINE.conf

require conf/image-uefi.conf

# The distro is created to support encrypted at rest for partitions except
# partition1 and partition2. The partition1 is mounted to /efi and the
# partition2 is mounted to /boot; neither partition is encrypted at rest.
# This is generally the best practice with a modern linux distro using
# systemd.

# efi prefix /efi or /boot/efi
EFI_PREFIX = "/boot/efi"

# meta-secure-core /efi/EFI/BOOT or /boot/efi/EFI/BOOT
EFI_BOOT_PATH = "${EFI_PREFIX}${EFIDIR}"

# systemd bootctl https://manpages.debian.org/bookworm/systemd-boot/bootctl.1.en.html
# --esp-path=${D}/efi --boot-path=${D}/boot --root=${D}

# ---
