# require conf/machine/include/machine-common.conf

# Used to define common build settings

# When creating or editing the package groups, generally a new group would
# be internal, and then added to an external meta group. When a specific use
# case is identified for external images, use an existing meta packagegroup
# as the template. Aspects of build-in inclusion are denoted with the use
# of an OVERRIDE from DISTROOVERRIDES or MACHINEOVERRIDES. Where functionality
# is only available from a specific Yocto meta-* layer, incorporate the \
# appropriate conditional checks and test with that layer absent.

# OVERRIDES                 Description
# none                      default packagegroup, required even if empty
# :machine-systemd-boot     additions for systemd-boot
# :libc-glibc               additions for runtime glibc, locales
# :libc-musl                additions for runtime musl
# :<machine_arch>           additions for specific MACHINE
# :intel-x86-common         additions for machine
# :corei7-64-intel-common   additions for machine
# :raspberrypi              additions for machine
# :tegra                    additions for machine

# inherit in image recipes (per image)
# INHERIT += " image_types_partition"

KERNEL_IMAGE_MAXSIZE = "32768"
# KERNEL_IMAGETYPE = "bzImage"
KERNEL_ARTIFACT_BIN_EXT = ""

# KERNEL_SPLIT_MODULES = "1"
# KERNEL_PACKAGE_NAME = "kernel"
KERNEL_VERSION_NAME = ""
# KERNEL_MODULE_PACKAGE_PREFIX = ""
KERNEL_MODULE_PACKAGE_SUFFIX = ""

IMAGE_NAME_SUFFIX = ""
# IMAGE_MACHINE_SUFFIX = ""

IMAGE_OVERHEAD_FACTOR = "1.2"
# maximum size of the rootfs KiB (4GiB=4194304, 8GiB=8388608, 16GiB=16777216)
IMAGE_ROOTFS_MAXSIZE = "16777216"
# remove extra space added by rootfs_rpm.bbclass
IMAGE_ROOTFS_EXTRA_SPACE:append = "${@bb.utils.contains('PACKAGE_INSTALL', 'dnf', ' - 102400', '', d)}"

# EXTRA_IMAGEDEPENDS:append = " ovmf"
# OVMF_SECURE_BOOT_EXTRA_FLAGS:x86-64 = "-D SMM_REQUIRE"

# meta-intel uefi-sign.bbclass
IMAGE_FEATURES[validitems] += "secureboot"
IMAGE_FEATURES += "secureboot"
SECURE_BOOT_SIGNING_CERT ?= "${METADIR}/meta-distro/files/user-keys/uefi_sb_keys/db.crt"
SECURE_BOOT_SIGNING_KEY ?= "${METADIR}/meta-distro/files/user-keys/uefi_sb_keys/db.key"

# insert per recipe that require signed EFI files:
# meta-intel
# inherit ${@bb.utils.contains('IMAGE_FEATURES', 'secureboot', 'uefi-sign', '', d)}

# meta-security/meta-integrity
MODSIGN_PRIVKEY ?= "${METADIR}/meta-distro/files/user-keys/modsign_keys/modsign_key.key"
MODSIGN_X509 ?= "${METADIR}/meta-distro/files/user-keys/modsign_keys/modsign_key.crt"
INHERIT += "${@bb.utils.contains('DISTRO_FEATURES', 'modsign', 'kernel-modsign', '', d)}"

# ---
